In [1]:
# https://www.kaggle.com/datasets/carrie1/ecommerce-data

In [2]:
import pandas as pd

In [3]:
! pip install kaggle

Requirement already satisfied: kaggle in c:\python\python312\lib\site-packages (2.2.4)
Requirement already satisfied: bleach in c:\python\python312\lib\site-packages (from kaggle) (6.4.0)
Requirement already satisfied: jupytext in c:\python\python312\lib\site-packages (from kaggle) (1.19.5)
Requirement already satisfied: kagglesdk<1.0,>=0.1.35 in c:\python\python312\lib\site-packages (from kaggle) (0.1.37)
Requirement already satisfied: packaging in c:\python\python312\lib\site-packages (from kaggle) (26.3)
Requirement already satisfied: protobuf in c:\python\python312\lib\site-packages (from kaggle) (7.35.1)
Requirement already satisfied: python-dateutil in c:\python\python312\lib\site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-dotenv in c:\python\python312\lib\site-packages (from kaggle) (1.2.3)
Requirement already satisfied: python-slugify in c:\python\python312\lib\site-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in c:\python\python312\lib\site-packages (from kaggle) (2.34.2)
Requirement already satisfied: tqdm in c:\python\python312\lib\site-packages (from kaggle) (4.70.0)
Requirement already satisfied: urllib3>=1.15.1 in c:\python\python312\lib\site-packages (from kaggle) (2.7.0)
Requirement already satisfied: webencodings in c:\python\python312\lib\site-packages (from bleach->kaggle) (0.6.1)
Requirement already satisfied: markdown-it-py>=1.0 in c:\python\python312\lib\site-packages (from jupytext->kaggle) (4.2.0)
Requirement already satisfied: mdit-py-plugins in c:\python\python312\lib\site-packages (from jupytext->kaggle) (0.6.1)
Requirement already satisfied: nbformat in c:\python\python312\lib\site-packages (from jupytext->kaggle) (5.11.0)
Requirement already satisfied: pyyaml in c:\python\python312\lib\site-packages (from jupytext->kaggle) (6.0.3)
Requirement already satisfied: six>=1.5 in c:\python\python312\lib\site-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in c:\python\python312\lib\site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\python\python312\lib\site-packages (from requests->kaggle) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in c:\python\python312\lib\site-packages (from requests->kaggle) (3.18)
Requirement already satisfied: certifi>=2023.5.7 in c:\python\python312\lib\site-packages (from requests->kaggle) (2026.7.22)
Requirement already satisfied: colorama in c:\users\student\appdata\roaming\python\python312\site-packages (from tqdm->kaggle) (0.4.6)
Requirement already satisfied: mdurl~=0.1 in c:\python\python312\lib\site-packages (from markdown-it-py>=1.0->jupytext->kaggle) (0.1.2)
Requirement already satisfied: fastjsonschema>=2.15 in c:\python\python312\lib\site-packages (from nbformat->jupytext->kaggle) (2.22.2)
Requirement already satisfied: jsonschema>=2.6 in c:\python\python312\lib\site-packages (from nbformat->jupytext->kaggle) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\student\appdata\roaming\python\python312\site-packages (from nbformat->jupytext->kaggle) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in c:\users\student\appdata\roaming\python\python312\site-packages (from nbformat->jupytext->kaggle) (5.16.1)
Requirement already satisfied: attrs>=22.2.0 in c:\python\python312\lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\python\python312\lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\python\python312\lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in c:\python\python312\lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2026.6.3)
Requirement already satisfied: platformdirs>=2.5 in c:\users\student\appdata\roaming\python\python312\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (4.11.3)
Requirement already satisfied: typing-extensions>=4.4.0 in c:\users\student\appdata\roaming\python\python312\site-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat->jupytext->kaggle) (4.16.0)

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
! pip install kagglehub

Collecting kagglehub
  Downloading kagglehub-1.0.2-py3-none-any.whl.metadata (40 kB)
     ---------------------------------------- 0.0/40.1 kB ? eta -:--:--
     ---------- ----------------------------- 10.2/40.1 kB ? eta -:--:--
     ------------------- ------------------ 20.5/40.1 kB 131.3 kB/s eta 0:00:01
     ------------------- ------------------ 20.5/40.1 kB 131.3 kB/s eta 0:00:01
     ------------------- ------------------ 20.5/40.1 kB 131.3 kB/s eta 0:00:01
     ----------------------------- -------- 30.7/40.1 kB 109.5 kB/s eta 0:00:01
     ----------------------------- -------- 30.7/40.1 kB 109.5 kB/s eta 0:00:01
     -------------------------------------- 40.1/40.1 kB 100.5 kB/s eta 0:00:00
Requirement already satisfied: kagglesdk<1.0,>=0.1.22 in c:\python\python312\lib\site-packages (from kagglehub) (0.1.37)
Requirement already satisfied: packaging in c:\python\python312\lib\site-packages (from kagglehub) (26.3)
Requirement already satisfied: pyyaml in c:\python\python312\lib\site-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in c:\python\python312\lib\site-packages (from kagglehub) (2.34.2)
Requirement already satisfied: tqdm in c:\python\python312\lib\site-packages (from kagglehub) (4.70.0)
Requirement already satisfied: protobuf in c:\python\python312\lib\site-packages (from kagglesdk<1.0,>=0.1.22->kagglehub) (7.35.1)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\python\python312\lib\site-packages (from requests->kagglehub) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in c:\python\python312\lib\site-packages (from requests->kagglehub) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in c:\python\python312\lib\site-packages (from requests->kagglehub) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\python\python312\lib\site-packages (from requests->kagglehub) (2026.7.22)
Requirement already satisfied: colorama in c:\users\student\appdata\roaming\python\python312\site-packages (from tqdm->kagglehub) (0.4.6)
Downloading kagglehub-1.0.2-py3-none-any.whl (70 kB)
   ---------------------------------------- 0.0/70.6 kB ? eta -:--:--
   ---------------------------------------- 0.0/70.6 kB ? eta -:--:--
   ----- ---------------------------------- 10.2/70.6 kB ? eta -:--:--
   ----------------- ---------------------- 30.7/70.6 kB 435.7 kB/s eta 0:00:01
   ----------------------- ---------------- 41.0/70.6 kB 326.8 kB/s eta 0:00:01
   ---------------------------------- ----- 61.4/70.6 kB 297.7 kB/s eta 0:00:01
   ---------------------------------- ----- 61.4/70.6 kB 297.7 kB/s eta 0:00:01
   ---------------------------------------- 70.6/70.6 kB 275.8 kB/s eta 0:00:00
Installing collected packages: kagglehub
Successfully installed kagglehub-1.0.2

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("carrie1/ecommerce-data")

print("Path to dataset files:", path)

c:\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Downloading to C:\Users\Student\.cache\kagglehub\datasets\carrie1\ecommerce-data\1.archive...

100%|██████████| 7.20M/7.20M [00:01<00:00, 3.85MB/s]

Extracting files...

Path to dataset files: C:\Users\Student\.cache\kagglehub\datasets\carrie1\ecommerce-data\versions\1

In [6]:
path

'C:\\Users\\Student\\.cache\\kagglehub\\datasets\\carrie1\\ecommerce-data\\versions\\1'

In [7]:
import os
os.listdir(path)

['data.csv']

In [8]:
import os
# encoding="ISO-8859-1" cần vì dataset này có ký tự đặc biệt (tên nước, mô tả sản phẩm). Không dùng thì dễ lỗi UnicodeDecodeError

df = pd.read_csv(os.path.join(path, "data.csv"), encoding="ISO-8859-1")
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

## **Group 1: Data Profiling**

### **1. Cấu trúc dữ liệu**

In [9]:
print("Số dòng, số cột: ", df.shape)
print("\n Tên cột dưới dạng list: ", df.columns.tolist())
print("\n Tên cột dưới dạng liệt kê: ", ", ".join(df.columns.tolist()))

Số dòng, số cột:  (541909, 8)

 Tên cột dưới dạng list:  ['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'UnitPrice', 'CustomerID', 'Country']

 Tên cột dưới dạng liệt kê:  InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID, Country

In [10]:
df.dtypes

InvoiceNo          str
StockCode          str
Description        str
Quantity         int64
InvoiceDate        str
UnitPrice      float64
CustomerID     float64
Country            str
dtype: object

In [11]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  str
 1   StockCode    541909 non-null  str
 2   Description  540455 non-null  str
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  str
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: float64(2), int64(1), str(5)
memory usage: 33.1 MB
None

In [12]:
df['CustomerID'].isnull().sum()

np.int64(135080)

In [13]:
print(", ".join(df.columns))

InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID, Country

### **2. Thống kê mô tả + số giá trị unique**

In [14]:
# Slide 1 — describe() là gì?
# VN: Tóm tắt cột số (và datetime nếu đã convert) thành 8 con số. Không phân tích hết dataset

df.describe()

            Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

In [15]:
# chia ra thành 4 nhóm
# 1. đầy đủ count
# 2. Tâm: trung bình, trung vị 
# điểm khác nhau: 
    # - mean: trung bình cộng
    # - median: trung vị
    # - mode: số xuất hiện nhiều nhất

# 3. Biên: min, max, range
# 4. phân tán: std, var, skew, kurt
# - std: độ lệch chuẩn
# - var: phương sai
# - skew: độ lệch
# - kurt: độ nhọn

In [16]:
a=pd.Series([1,2,3,4,5])
print(a.var())
print(a.std())
print(a.skew())
print(a.kurt())

2.5
1.5811388300841898
0.0
-1.2000000000000002

In [17]:
from scipy import stats

for col in df[['Quantity', 'UnitPrice']]:
    mean_ = df[col].mean()
    median_ = df[col].median()
    skew_ = stats.skew(df[col])
    kurt_ = stats.kurtosis(df[col])  # mặc định đã là Excess Kurtosis (fisher=True)
    print(f"{col}: mean={mean_:.2f}, median={median_:.2f}, skew={skew_:.2f}, kurtosis={kurt_:.2f}")

Quantity: mean=9.55, median=3.00, skew=-0.26, kurtosis=119768.05
UnitPrice: mean=4.61, median=2.08, skew=186.51, kurtosis=59005.17

In [18]:
df.describe()

            Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

In [19]:
df.describe(percentiles=[.01, .05, .1, .25, .5, .75, .9, .95, .99])

            Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
1%         -2.000000       0.190000   12415.000000
5%          1.000000       0.420000   12626.000000
10%         1.000000       0.630000   12876.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
90%        24.000000       7.950000   17719.000000
95%        29.000000       9.950000   17905.000000
99%       100.000000      18.000000   18212.000000
max     80995.000000   38970.000000   18287.000000

In [20]:
df.describe(exclude="datetime")

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
count,541909,541909,540455,541909.000000,541909,541909.000000,406829.000000,541909
unique,25900,4070,4223,NaN,23260,NaN,NaN,38
top,573585,85123A,WHITE HANGING HEART T-LIGHT HOLDER,NaN,10/31/2011 14:41,NaN,NaN,United Kingdom
freq,1114,2313,2369,NaN,1114,NaN,NaN,495478
mean,NaN,NaN,NaN,9.552250,NaN,4.611114,15287.690570,NaN
std,NaN,NaN,NaN,218.081158,NaN,96.759853,1713.600303,NaN
min,NaN,NaN,NaN,-80995.000000,NaN,-11062.060000,12346.000000,NaN
25%,NaN,NaN,NaN,1.000000,NaN,1.250000,13953.000000,NaN
50%,NaN,NaN,NaN,3.000000,NaN,2.080000,15152.000000,NaN
75%,NaN,NaN,NaN,10.000000,NaN,4.130000,16791.000000,NaN
max,NaN,NaN,NaN,80995.000000,NaN,38970.000000,18287.000000,NaN

In [21]:
# 3. Thống kê mô tả + số giá trị unique
print("Thống kê cột số:")
print(df.describe())

print("\nSố giá trị unique:")
print(df.nunique())

print("\nSố hóa đơn:", df["InvoiceNo"].nunique())
print("Số khách hàng (bỏ NA):", df["CustomerID"].nunique())
print("Số sản phẩm (StockCode):", df["StockCode"].nunique())
print("Số quốc gia:", df["Country"].nunique())
print("\nTop 10 quốc gia:")
print(df["Country"].value_counts().head(10))

Thống kê cột số:
            Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

Số giá trị unique:
InvoiceNo      25900
StockCode       4070
Description     4223
Quantity         722
InvoiceDate    23260
UnitPrice       1630
CustomerID      4372
Country           38
dtype: int64

Số hóa đơn: 25900
Số khách hàng (bỏ NA): 4372
Số sản phẩm (StockCode): 4070
Số quốc gia: 38

Top 10 quốc gia:
Country
United Kingdom    495478
Germany             9495
France              8557
EIRE                8196
Spain               2533
Netherlands         2371
Belgium             2069
Switzerland         2002
Portugal            1519
Australia           1259
Name: count, dtype: int64

In [22]:
# 4. Thời gian + dấu hiệu dữ liệu bẩn
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])

print("Từ ngày:", df["InvoiceDate"].min())
print("Đến ngày:", df["InvoiceDate"].max())

print("\nQuantity < 0 (thường là hủy đơn):", (df["Quantity"] < 0).sum())
print("UnitPrice < 0 (lỗi / điều chỉnh):", (df["UnitPrice"] < 0).sum())
print("UnitPrice = 0:", (df["UnitPrice"] == 0).sum())

cancelled = df["InvoiceNo"].astype(str).str.startswith("C")
print("Hóa đơn hủy (InvoiceNo bắt đầu bằng C):", cancelled.sum())

print("\nMẫu dòng Quantity âm:")
df[df["Quantity"] < 0].head()

Từ ngày: 2010-12-01 08:26:00
Đến ngày: 2011-12-09 12:50:00

Quantity < 0 (thường là hủy đơn): 10624
UnitPrice < 0 (lỗi / điều chỉnh): 2
UnitPrice = 0: 2515
Hóa đơn hủy (InvoiceNo bắt đầu bằng C): 9288

Mẫu dòng Quantity âm:

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom

### **Group 2: Data Cleaning (làm sạch dữ liệu)**

Xử lý trùng lặp, missing, kiểu dữ liệu, giao dịch hủy / giá âm, rồi tạo cột `TotalPrice`.

In [23]:
# Làm sạch trên bản sao, giữ nguyên df gốc
df_clean = df.copy()

# 1. Xóa dòng trùng
df_clean = df_clean.drop_duplicates()

# 2. Bỏ dòng thiếu CustomerID hoặc Description
df_clean = df_clean.dropna(subset=["CustomerID", "Description"])

# 3. Đổi kiểu dữ liệu
df_clean["InvoiceDate"] = pd.to_datetime(df_clean["InvoiceDate"])
df_clean["CustomerID"] = df_clean["CustomerID"].astype(int)
df_clean["InvoiceNo"] = df_clean["InvoiceNo"].astype(str)
df_clean["Description"] = df_clean["Description"].str.strip()

# 4. Chỉ giữ giao dịch hợp lệ: mua hàng thật (số lượng > 0, giá > 0)
#    InvoiceNo bắt đầu bằng C = đơn hủy
df_clean = df_clean[~df_clean["InvoiceNo"].str.startswith("C")]
df_clean = df_clean[(df_clean["Quantity"] > 0) & (df_clean["UnitPrice"] > 0)]

# 5. Tạo cột doanh thu
df_clean["TotalPrice"] = df_clean["Quantity"] * df_clean["UnitPrice"]

print("Trước khi clean:", df.shape)
print("Sau khi clean :", df_clean.shape)
df_clean.head()

Trước khi clean: (541909, 8)
Sau khi clean : (392692, 9)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34

In [24]:
# Kiểm tra lại chất lượng sau khi clean
print("Missing còn lại:")
print(df_clean.isnull().sum())

print("\nDòng trùng còn lại:", df_clean.duplicated().sum())
print("Quantity <= 0:", (df_clean["Quantity"] <= 0).sum())
print("UnitPrice <= 0:", (df_clean["UnitPrice"] <= 0).sum())

print("\nTổng doanh thu:", round(df_clean["TotalPrice"].sum(), 2))
print("Số khách hàng:", df_clean["CustomerID"].nunique())
print("Số hóa đơn:", df_clean["InvoiceNo"].nunique())
df_clean.info()

Missing còn lại:
InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
TotalPrice     0
dtype: int64

Dòng trùng còn lại: 0
Quantity <= 0: 0
UnitPrice <= 0: 0

Tổng doanh thu: 8887208.89
Số khách hàng: 4338
Số hóa đơn: 18532
<class 'pandas.DataFrame'>
Index: 392692 entries, 0 to 541908
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    392692 non-null  str
 1   StockCode    392692 non-null  str
 2   Description  392692 non-null  str
 3   Quantity     392692 non-null  int64
 4   InvoiceDate  392692 non-null  datetime64[us]
 5   UnitPrice    392692 non-null  float64
 6   CustomerID   392692 non-null  int64
 7   Country      392692 non-null  str
 8   TotalPrice   392692 non-null  float64
dtypes: datetime64[us](1), float64(2), int64(2), str(4)
memory usage: 30.0 MB

In [25]:
# 2. Giá trị thiếu và dòng trùng
missing = df.isnull().sum()
missing_pct = (missing / len(df) * 100).round(2)

quality = pd.DataFrame({
    "so_thieu": missing,
    "ty_le_%": missing_pct
})
print("Giá trị thiếu theo cột:")
print(quality[quality["so_thieu"] > 0])

print("\nSố dòng trùng hoàn toàn:", df.duplicated().sum())
print("Tỷ lệ dòng trùng: {:.2f}%".format(df.duplicated().sum() / len(df) * 100))

Giá trị thiếu theo cột:
             so_thieu  ty_le_%
Description      1454     0.27
CustomerID     135080    24.93

Số dòng trùng hoàn toàn: 5268
Tỷ lệ dòng trùng: 0.97%